# Generated by Django 3.1.1 on 2020-09-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('poster', models.FileField(upload_to='events/')),
                ('schedule', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Past', 'Past')], max_length=20)),
            ],
        ),
    ]
