# Generated by Django 3.1.1 on 2020-09-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('event', models.ForeignKey(limit_choices_to={'schedule': 'Upcoming'}, on_delete=django.db.models.deletion.CASCADE, to='website.event')),
            ],
        ),
    ]
