# Generated by Django 3.1.1 on 2020-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
